### ISSUE TITLE
Do not retry to auth with Duo if too many failures are recorded, while using push

### ISSUE THREAD

**Issue by gdestuynder** [mozilla-it/duo_openvpn#17]
Issue:
- User uses push Duo 2FA and authenticate (password is then 'push').
- VPN client records the 'push' password
- VPN disconnects
- VPN reconnects and use the saved 'push' password, causing a Duo 2FA push prompt
- User is sleeping/out/busy and does not notice, Duo 2FA push authentication timeout (=authentication failure)
- VPN client keeps retrying
- Duo lockout the account due to too many retries
- User is locked out until admins verify and unlock the user

In order to make this better for users, I would propose to:
- Establish a counter which increments per user for all failed authentication using push
- If the counter reaches X within a certain amount of time (say, 3 failures in 5min for ex.), fail subsequent authentications on to the VPN for the next Y amount of time (10min for ex) without contacting Duo for that user

This would alleviate the user being locked out on subsequent push retries, though it also means that if the user comes back within the 10min period they wont be able to login for 10min (unless they use something else than push, such as an OTP, which will still work every time).

**Comment by gcoxmoz** [comment]
> VPN client keeps retrying

The next generation of our vpn client config is going to have 'connect-retry-max 3' to mitigate issues along this line (why we never had it, beats me).  Not that that eliminates this issue from happening, but it would severely reduce the likelihood.

**Comment by gdestuynder** [comment]
indeed i think that would be a sufficient fix regardless

**Comment by gcoxmoz** [comment]
The VPN itself can-trivially/should limit your failures-per-session, and our VPN was relaunched with connect-retry-max to do that.

The greater question in this issue is failures-per-time.  We've fixed the case of "I fell asleep and it kept trying and I woke up locked out."  We've left exposed the case of "try. try. try some more."

Asked endusersupport manager about the lockout frequency:
> "Most of the support we do is for users that switch or brick their devices.  It looks like one a week for lockouts."

It's unclear that we (the VPN) are a majority cause of lockouts anymore.  As such, I'm going to decline this work: I don't know that I want to get into this script keeping state, and I think it adds code complexity without real benefit that I can see.

But I could be argued off that.
