### ISSUE TITLE
Support using YubiAES without "passcode:" prefix

### ISSUE THREAD

**Issue by edmorley** [mozilla-it/duo_openvpn#9]
Once 2FA is mandatory when using Mozilla VPN, duo_openvpn no longer needs to support the username+password case. As such it should no longer be necessary to make people prefix their YubiAES style OTPs with `passcode:`, in order to differentiate between them and passwords, here:
https://github.com/mozilla-it/duo_openvpn/blob/43547f3474872fbccccf4e2154f0d84bad1d5cbf/duo_openvpn.py#L265-L267

[If this fork wants to be as generic as possible (so non-Mozilla entities can use it), then perhaps we can still do the above, but just put it behind a pref - so at least Mozilla can get the benefit.]

Thanks! :-)

Note: If this change is made, the docs should be updated here too:
https://mana.mozilla.org/wiki/pages/viewpage.action?pageId=40049559

**Comment by gdestuynder** [comment]
Note: there is an exception mode that still uses LDAP password to authenticate thus this use case should still work, no matter the change.

Another thing I was thinking about would be to actually detect the YubiAES since it's modhex, it is potentially feasible. I just haven't done it ;-)
The real reason thought is that I was hoping for https://github.com/mozilla/openvpn to be merged upstream, since it makes such implementations a lot cleaner (and also has session support.. \o/)

**Comment by edmorley** [comment]
Ah makes sense :-)
